name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: lib

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: lib

  build-cmake:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-cmake
        path: lib

  build-cmake-msvc:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build .
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: lib

  build-cmake-mingw:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: sudo apt-get install mingw-w64
    - name: cmake
      run: cmake -DCMAKE_TOOLCHAIN_FILE=i686-w64-mingw32.cmake .
    - name: make
      run: make
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mingw
        path: lib
